@startuml

title AIF Project Package Structure

package aif_model {

    package generative_model {
        class likelihood
        class transitions
        class preferences
    }

    package inference {
        class vfe
        class posterior
    }

    package planning {
        class efe
        class policy_selection
    }

    package environment {
        class bar_chart_env
    }

    package visualization {
        class belief_heatmaps
    }

}

@enduml