@startuml

class PymdpAgent {
    A
    B
    C
    D
    policies
}

class BarChartAIFAgent {
    + buildA()
    + buildB()
    + buildC()
    + runEpisode()
}

BarChartAIFAgent --|> PymdpAgent

@enduml